# Generated by Django 3.2.8 on 2021-10-12 00:05

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicians', '0002_auto_20211011_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='friends',
            field=models.ManyToManyField(blank=True, to='musicians.Musician'),
        ),
        migrations.AddField(
            model_name='musician',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='None', editable=False, populate_from='user'),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
