# Generated by Django 3.2.8 on 2021-10-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0003_auto_20211011_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='slug',
        ),
    ]
