# Generated by Django 3.2.8 on 2021-10-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0004_remove_musician_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='video',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
