# Generated by Django 3.2.8 on 2021-10-19 16:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicians', '0006_auto_20211019_1248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendRequest',
            new_name='BandRequest',
        ),
    ]
